"""Persist the evidence and adaptation scope beside every experiment."""
MODEL_INFO = {
    "emoe2025": {
        "label": "EMOE code-based dense modality routing and online unimodal feature distillation",
        "fidelity": "official_code_checked; cached_feature_classification_and_mask_adaptation",
        "source": "https://openaccess.thecvf.com/content/CVPR2025/html/Fang_EMOE_Modality-Specific_Enhanced_Dynamic_Emotion_Experts_CVPR_2025_paper.html",
        "code": "https://github.com/fuyyyyy/EMOE/tree/c4759c748105e18354cd9082b1d8c6d310f1f9d8",
        "limitations": ["Cached BERT, kernel-1 projections, last-observed readout and noncausal masked attention",
                        "Router retains raw flattened features but uses a configurable bottleneck instead of input_dim/8",
                        "Three-class CE and Brier-error importance are adaptations of the released regression/L1/squared-error code",
                        "Feature-softmax MSE and normalized inverse-error importance follow released code where paper notation differs",
                        "Missing branches are masked; this is not a missing-modality generation or frozen-teacher method"],
    },
    "ren2021": {
        "label": "IMAN components / single-entity within-sample adaptation",
        "fidelity": "abstract_verified_components; full_equations_not_verified",
        "source": "https://doi.org/10.1109/LSP.2021.3078698",
        "limitations": ["No conversation grouping or speaker IDs", "State equations are an explicit implementation design"],
    },
    "zheng2022": {
        "label": "Cascade multi-head attention and shared-latent autoencoder adaptation",
        "fidelity": "full_method_checked; cached_feature_and_training_adaptation",
        "source": "https://doi.org/10.1109/TMM.2022.3144885",
        "limitations": ["Reconstructs cached features; compact residual encoders and masked pooling",
                       "Configurable reconstruction warmup and supervised fine-tuning; see saved phase weights",
                       "Missing-modality fallback is a dataset adaptation"],
    },
    "pan2020": {
        "label": "Nine modality-axis attention relations with four prediction subnetworks",
        "fidelity": "full_method_checked; within_sample_and_joint_training_adaptation",
        "source": "https://www.isca-archive.org/interspeech_2020/pan20b_interspeech.pdf",
        "limitations": ["Joint subnetwork supervision replaces separate frozen-subnetwork training", "Within-sample time axis"],
    },
    "m3er2020": {
        "label": "CCA screening, sourced proxies, memory and multiplicative objective adaptation",
        "fidelity": "full_method_checked; independent_proxy_and_backbone_design",
        "source": "https://arxiv.org/html/1911.05659v2",
        "limitations": ["Train-only paired ridge proxies replace original construction", "Compact independently implemented memory backbone"],
    },
    "mfrm2022": {
        "label": "MFRM-inspired residual-memory baseline",
        "fidelity": "inspired_baseline; original_equations_not_verified",
        "source": "https://doi.org/10.1109/TAFFC.2020.3000510",
        "limitations": ["Accessible author repository has README only", "Interaction, intensity gating and residual recurrence are explicit design choices"],
    },
    "transmodality2020": {
        "label": "Parallel forward/back translation with four reconstruction losses",
        "fidelity": "paper_architecture_checked; cached_feature_and_within_sample_adaptation",
        "source": "https://arxiv.org/pdf/2009.02902",
        "limitations": ["Within-sample slots and masked pooling replace video-level utterance sequences and per-utterance labels",
                        "Observed-target non-autoregressive decoder; causal masking/target shifting not specified in paper",
                        "Shared text context encoder across the two cells; dimensions and loss weights are adaptation settings",
                        "Cannot be used as a source-only missing-modality generator"],
    },
    "memobert2022": {
        "label": "MEmoBERT-inspired cached-feature masking and soft-prompt model",
        "fidelity": "inspired_baseline; cached_feature_soft_prompt_adaptation; no_original_pretrained_checkpoint",
        "source": "https://arxiv.org/pdf/2111.00865",
        "limitations": ["Randomly initialized joint Transformer; cached contextual BERT differs from token embedding input",
                        "Three feature MSE tasks replace whole-word vocabulary MLM and AV reconstruction; no FER teacher KL task",
                        "Learned soft tokens and a new class/regression head replace the paper's hard prompt and reused vocabulary head",
                        "Cached BERT contains context before masking; no claim of token-level MLM or causal word attribution",
                        "Training-split reconstruction warmup is not the original large-scale multimodal pretraining"],
    },
    "hycon2022": {
        "label": "HyCon arXiv-v1 hybrid contrastive objectives and additive fusion",
        "fidelity": "arxiv_v1_method_checked; final_journal_pair_selection_not_reproduced",
        "source": "https://arxiv.org/pdf/2109.01797v1",
        "limitations": ["Uses v1 objectives; final-journal pair-selection mechanism not reproduced",
                        "Cached BERT and a separate text Transformer replace text BERT fine-tuning",
                        "Softplus ensures nonnegative cosine scores; added projection is an implementation choice",
                        "Available-anchor averages replace batch sums and omit anchors without positive partners",
                        "Classification CE and regression score>=0 pair groups are explicit adaptation settings"],
    },
}
